version: '3'

volumes:
  bundle:
  node_modules:
  attachment:
  db:
  nginx-certs:
  nginx-dhparam:
  nginx-vhost:
  nginx-html:
  active_storage:

services:
  db:
    image: postgres:12.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: UPDATE_ME

  app: &rails
    image: ilabsea/chatfuel:0.1
    restart: unless-stopped
    volumes:
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - attachment:/app/public/uploads
      - active_storage:/app/storage
    # tmpfs: /app/tmp
    depends_on:
      - db
      - redis
    environment:
      - GUISSO_CLIENT_ID=
      - GUISSO_CLIENT_SECRET=
      - LANG=C.UTF-8
      - DATABASE_URL=postgres://postgres:UPDATE_ME@db/chatfuel_production
      - REDIS_URL=redis://redis:6379
      - RAILS_MAX_THREADS=15
      - PIDFILE=tmp/server.pid
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_MASTER_KEY=UPDATE_ME
      - VIRTUAL_HOST=owso.ilabsea.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=owso.ilabsea.org
      - LETSENCRYPT_EMAIL=kakada@instedd.org
      - FACEBOOK_PAGE_ID=
      - FACEBOOK_APP_ID=
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
    command:
      - /bin/sh
      - -c
      - bundle exec puma -e production -b tcp://0.0.0.0:80

  redis:
    image: redis:5.0.7

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-dhparam:/etc/nginx/dhparam
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-dhparam:/etc/nginx/dhparam
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
